name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate action.yml
        run: |
          if [ -f action.yml ]; then
            echo "Validating action.yml..."
            grep -q '^name: DMD Cloud Production Deploy$' action.yml || (echo "Unexpected action name in action.yml." && exit 1)
          else
            echo "action.yml not found."
            exit 1
          fi
